[project]
name = "bs-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.122.0",
    "icalendar>=6.3.2",
    "recurring-ical-events>=3.8.0",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
